// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuneoeqlfotpipvqinon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1bmVvZXFsZm90cGlwdnFpbm9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODU5MjcsImV4cCI6MjA3MTI2MTkyN30.UYgBYLi1j-ZUYO4-hEUbOkU9dOrkxhM2Kjt_8pekxHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});